services:
  # db:
  #   image: postgres:15-alpine
  #   container_name: iot_db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=iot_db
  #   ports:
  #     - "5432:5432"

  api:
    build: .
    container_name: iot_api
    # depends_on:
    #   - db
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=sqlite:///app.db
    command: ["uv run alembic upgrade head", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_data:
